# Generated by Django 4.2 on 2023-04-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='profile',
            new_name='profile_id',
        ),
    ]
