# Generated by Django 4.2 on 2023-04-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0002_rename_profile_comment_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
